from .arthemy_model_live_tuner_zit import NODE_CLASS_MAPPINGS as MODEL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_NAMES
from .arthemy_qwenTE_live_tuner_zit import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_NAMES
from .arthemy_model_live_tuner_zit_LAB import NODE_CLASS_MAPPINGS as MODEL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_NAMES
from .arthemy_qwenTE_live_tuner_zit_LAB import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_NAMES

NODE_CLASS_MAPPINGS = {**MODEL_MAPPINGS, **CLIP_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MODEL_NAMES, **CLIP_NAMES}


__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
